### PR TITLE
Submit new comp(ali)

### PR DESCRIPTION
**Pull request by ali10ma**

### CODE REVIEW

**Comment by Kevin-Benelli** [comment]
Merging with known issue for insert statement. We will resolve this issue upon next MR

**Comment by ali10ma** [comment]
> Merging with known issue for insert statement. We will resolve this issue upon next MR

what was the issue with the insert statement?

**Comment by Kevin-Benelli** [comment]
1. The submit button does not insert into DB as of right now. 


Looking into it more now, however.

**Comment by ali10ma** [comment]
> 1. The submit button does not insert into DB as of right now.
> 2. I noticed that we were using document.getElementById("compID").value; to parse the data, which doesn't work with JSP, instead we have to use request.getParameter("ID_NAME");
> 
> Looking into it more now, however.

Yes, the submit button does not insert into DB yet as in our last discussion.

Is request.getParameter("ID_NAME"); working on your side? I tried it on my side, but I do not see it is working yet.

**Pull request merged**
